version: "3.2"

services:
  dev:
    container_name: gently-node
    image: paritytech/ci-linux:974ba3ac-20201006
    working_dir: /gently-node
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/gently-node/.cargo
    volumes:
      - .:/gently-node
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/gently --dev --ws-external"
